### ISSUE TITLE
Issue: In registration form page, password text is visible in the field

### ISSUE THREAD

**Issue by vrun1208** [NidhiSharma63/Todo#30]
In Registration form page `Register.jsx` password and confirmPassword field are not set to `type=password` that makes the password visible while entered by user.
Same issue in the LoginPage too.

### **Actual output**
![2023-09-13](https://github.com/NidhiSharma63/task-master/assets/58364635/0d9b1d99-fcb2-4437-8243-7b242b42f302)

### **Expected output**
![2023-09-13 (1)](https://github.com/NidhiSharma63/task-master/assets/58364635/e9c4c21e-0fd7-4bae-981d-69c322a0a781)

PS: Currently working on this issue, will soon open a PR!

**Comment by NidhiSharma63** [comment]
@vrun1208 Thank you so much for your efforts. I really appreciate your PR
