### ISSUE TITLE
Text field does not get disappear 

### ISSUE THREAD

**Issue by NidhiSharma63** [NidhiSharma63/Todo#39]
While create new section then text fields appear but it won't go if you don't put any into it and just clicked anywhere on the screen.

**Steps to reproduce**
Click on add section icon then don't put anything just clicked inside the textarea then click outside (on window). now if text area is empty then it' should get disappear. but it won't.

**Expected output**

if user click on outside without entering the value then it should the textarea should get disappear.

**Comment by aman123573** [comment]
@NidhiSharma63 Hi there , i would like to work on this , please assign it to me. Thanks

**Comment by NidhiSharma63** [comment]
@aman123573 sure! you can work on this

**Comment by aman123573** [comment]
I am getting these errors :
1 . react-dom.development.js:86 Warning: Cannot update a component (`BackDropLoaderContextComp`) while rendering a different component (`Login`). To locate the bad setState() call inside `Login`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render . 
2 . xhr.js:251     POST http://localhost:3000/login 404 (Not Found)
Can you help me out fixing these

**Comment by NidhiSharma63** [comment]
@aman123573 this is not the api `http://localhost:3000/login`. api should be like this http://localhost:3000/api/v1login.
have you configured the backend ??

**Comment by aman123573** [comment]
@NidhiSharma63 I am new in backend , so i don't know what configurations have to do.. If you could suggest me some more hints i can start

**Comment by NidhiSharma63** [comment]
@aman123573  Create a free cluster on Mongodb. then copy the .env-template into .evn for both frontend and backend folders. Then get the mongodb url set mongodb url in backend .env file and set PORT to 3000, leave other env filed as it is. Start the backend using `npm start`  button. then go to frontend folder copy the .env-template to .env. set the URL `http://localhost:3000/api/v1`. and start frontend

**Comment by HimanshuParodiya** [comment]
@NidhiSharma63 Hi there, I would like to work on this

**Comment by NidhiSharma63** [comment]
@HimanshuParodiya Anyone can work on this i will merge the first working PR 🙌🙌

**Comment by HimanshuParodiya** [comment]
@NidhiSharma63  When I clicked on Add Task form appeared and disappeared correctly..

**Comment by NidhiSharma63** [comment]
@HimanshuParodiya have added the reference 
![bug gif](https://github.com/NidhiSharma63/task-master/assets/99652555/e623244d-86c4-492d-b681-0b955f2dce31)
